# .stylua.toml — Windows + tabs + "spaced out" tweaks
syntax = "All"
line_endings = "Windows"
indent_type = "Tabs"
indent_width = 4
column_width = 120
quote_style = "AutoPreferDouble"
space_after_function_names = "Always"
block_newline_gaps = "Never"
collapse_simple_statement = "Always"

[sort_requires]
enabled = true
